msmpi: Avoid Fortran 2008 idioms in Fortran 90 module
`TYPE(*), DIMENSION(..)` is a Fortran 2008 idiom. Using it in this module
causes issues downstream in Fortran 90 projects.
See, e.g.: https://github.com/ElmerCSC/elmerfem/pull/559

Use an extension of gfortran to mark polymorphic types in a way that is
compatible with Fortran 90.

Flang doesn't support polymorphic types currently. It fails when trying
to use them with an error like the following:
```
error: loc("C:/msys64/home/Markus/test_ignore_flang.f90":43:3): C:/M/B/src/flang-18.1.8.src/lib/Lower/CallInterface.cpp:949: not yet implemented: support for polymorphic types
LLVM ERROR: aborting
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: C:/msys64/clang64/bin/flang -fc1 -triple x86_64-w64-windows-gnu -emit-obj -fcolor-diagnostics -mrelocation-model pic -pic-level 2 -target-cpu x86-64 -mframe-pointer=none -o test_ignore_flang.o -x f95-cpp-input test_ignore_flang.f90
```
Don't include subroutines with polymorphic types in the MPI module for
LLVM Flang for the time being.