Revert "Try to build nspr/nss for clangarm64"
This reverts commit cb8dfab77063d8c06a836c09f12fad252984840d.

nspr fails with:

nspr-4.34/nspr/pr/include/md/_winnt.h:42:2: error: unknown processor architecture