qt6-static: turn on system harfbuzz
It's already being pulled in via freetype, apparently, because I get

 ld.lld: error: duplicate symbol: hb_font_funcs_create
 >>> defined at libQt6BundledHarfbuzz.a(hb-font.cc.obj)
 >>> defined at libharfbuzz.a(hb-font.cc.obj)