rust: Update to 1.61.0
Fixes a number of issues in compiler/rustc_llvm regarding lib handling.
This is a moving part in current rust releases...

- Disabled llvm-static-stdcpp
Fixes CLANG64 build error:
    thread 'main' panicked at 'assertion failed: !cxxflags.contains(\"stdlib=libc++\")', compiler\rustc_llvm\build.rs:351:13
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

- Removed `pthread` from forced libs in compiler/rustc_llvm/build.rs
`pthread` is also provided by llvm-config and having both now triggers an error about mixed link modifiers.
See https://github.com/rust-lang/rust/issues/97299

    $ llvm-config --system-libs --link-static
    -lpsapi -lshell32 -lole32 -luuid -ladvapi32 -lpthread -lz -lxml2

Note that `ffi` is still forced by the patch as llvm-config does not provide it.
See 0001-rustc-llvm-fix-libs.patch (replaces 0001-add-missing-libs.patch).

- Rebased 0007-clang-subsystem.patch