lldb: revert changes that cause issues with dllimported symbols (#28599)
Trying to build LLDB in GCC environments leads to the following link error:
```
  FAILED: [code=1] bin/liblldb.dll lib/liblldb.dll.a
  C:\Windows\system32\cmd.exe /C "cd . && D:\M\msys64\ucrt64\bin\g++.exe -march=nocona -msahf -mtune=generic -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wp,-D__USE_MINGW_ANSI_STDIO=1 -Wa,-mbig-obj -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -Wimplicit-fallthrough -Wno-nonnull -Wno-class-memaccess -Wno-dangling-reference -Wno-redundant-move -Wno-pessimizing-move -Wno-array-bounds -Wno-stringop-overread -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -ffunction-sections -fdata-sections -Wno-unknown-pragmas -Wno-strict-aliasing -Wno-stringop-truncation -O3 -DNDEBUG  -shared  -Wl,--gc-sections -o bin\liblldb.dll -Wl,--out-implib,lib\liblldb.dll.a -Wl,--major-image-version,22,--minor-image-version,1 @CMakeFiles\liblldb.rsp && C:\Windows\system32\cmd.exe /C "cd /D D:\W\B\src\build-UCRT64\source\API && D:\M\msys64\ucrt64\bin\cmake.exe -E create_symlink D:/M/msys64/ucrt64/lib/cmake/clang/../../..//lib/clang/22 D:/W/B/src/build-UCRT64/bin/clang""
  D:/M/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/15.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/liblldbPluginScriptInterpreterPythonInterfaces.a(ScriptedPythonInterface.cpp.obj):ScriptedPythonInterface.cpp:(.text$_ZN12lldb_private23ScriptedPythonInterface28ExtractValueFromPythonObjectISt10shared_ptrINS_15ValueObjectListEEEET_RNS_6python12PythonObjectERNS_6StatusE+0x84): undefined reference to `__imp__ZNK4lldb11SBValueList7GetSizeEv'
  D:/M/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/15.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/liblldbPluginScriptInterpreterPythonInterfaces.a(ScriptedPythonInterface.cpp.obj):ScriptedPythonInterface.cpp:(.text$_ZN12lldb_private23ScriptedPythonInterface28ExtractValueFromPythonObjectISt10shared_ptrINS_15ValueObjectListEEEET_RNS_6python12PythonObjectERNS_6StatusE+0xa0): undefined reference to `__imp__ZNK4lldb11SBValueList15GetValueAtIndexEj'
  D:/M/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/15.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/liblldbPluginScriptInterpreterPythonInterfaces.a(ScriptedPythonInterface.cpp.obj):ScriptedPythonInterface.cpp:(.text$_ZN12lldb_private23ScriptedPythonInterface28ExtractValueFromPythonObjectISt10shared_ptrINS_15ValueObjectListEEEET_RNS_6python12PythonObjectERNS_6StatusE+0xc2): undefined reference to `__imp__ZN4lldb7SBValueD1Ev'
  collect2.exe: error: ld returned 1 exit status
```

That is because `liblldbPluginScriptInterpreterPythonInterfaces.a` requires
the dllimported symbols from `liblldb.dll`. However, that static archive is
one of the sources for linking that dynamic library. That would probably
require that the static archive uses the symbols that aren't prefixed with
`__imp_`. But that static archive is also used for other binaries that *do*
link to the DLL. So, it should probably use the `__imp_` prefixed symbols for
those binaries.

Revert the changes that introduced that situation.

The followup patches have already been reverted in
https://github.com/llvm/llvm-project/commit/091296f3e338798c55d59014c3b4c265b8d6a653
These commits might have been forgotten in that revert.