pdcurses: Fix `_bool` is not declared error in C++.
Prior to this patch, C++ programs that include pdcurses headers hit this error:

  C:/MinGW/MSYS2/mingw64/include/pdcurses/curses.h:67:15: error: _bool was not declared in this scope; did you mean bool?
     67 | # define bool _bool
        |               ^~~~~

, which has been fixed by <https://sourceforge.net/p/pdcurses/code/ci/8e41f712184156fa4e0966c0c9b3b3fe0dc990be/>.

Signed-off-by: Liu Hao <lh_mouse@126.com>