ffmpeg: rebuild and backport a build fix
Fixes:
error: incompatible function pointer types initializing 'PFN_vkDebugUtilsMessengerCallbackEXT'

for clang32 since clang v16