volk: Fix running volk_modtool python script
This fixes the following runtime error.
ImportError: cannot import name 'volk_modtool' from partially initialized module 'volk_modtool' (most likely due to a circular import)