Disable clangarm64 for some packages which fail to build
mingw-w64-apr
    configure: error: could not determine the proper format for apr_ssize_t

mingw-w64-irrlicht
    ld.lld: error: undefined symbol: png_riffle_palette_neon

mingw-w64-srecord
    error: 'bin/srec_info.exe': No such file or directory

mingw-w64-winpty
    Error: could not find Cygwin/MSYS G++ compiler.  One of these should be in your PATH:

mingw-w64-pyside2
    qdragmoveevent_wrapper.cpp:221:73: error: no member named 'DragMove' in 'QOpenGLShader'

mingw-w64-libserdes
    CustomFields.hh:24:10: fatal error: '../impl/json/JsonDom.hh' file not found

mingw-w64-gdb
    BFD does not support target aarch64-w64-mingw32.

mingw-w64-openocd
    helper/replacements.h:148:39: error: invalid output constraint '=a' in asm

mingw-w64-magnum
    Utility/StlForwardTuple.h:58:10: error: '__tuple' file not found, did you mean 'tuple'?

mingw-w64-libgdata
    gdata/tests/buffer.c:41:2: error: call to undeclared function 'alarm'

mingw-w64-bsdfprocessor
    src/GraphScene.cpp:683:16: error: assigning to 'lb::Brdf *' from incompatible type 'std::shared_ptr<Brdf>'

mingw-w64-v8
    ERROR Unresolved dependencies.

mingw-w64-smpeg2
    Invalid configuration `aarch64-w64-mingw32': machine `aarch64-w64' not recognized

mingw-w64-smpeg
    Invalid configuration `aarch64-w64-mingw32': machine `aarch64-w64' not recognized

mingw-w64-skia
    ERROR at //gn/BUILDCONFIG.gn:136:14: Script returned non-zero exit code.

mingw-w64-shishi-git
    missing: line 81: help2man: command not found

mingw-w64-sgml-common
    ???

mingw-w64-openimagedenoise
    include/xmmintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"

mingw-w64-nodejs
    include/tmmintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"

mingw-w64-nim
    clang: error: no input files

mingw-w64-mtex2MML
    src/mtex2MML.h:54:35: error: a function declaration without a prototype is deprecated in all versions of C