gnatcoll-python: patch setup.py for building from volume with different letter
When building the package in the CI pipeline run by GitHub Actions,
the setup.py script fails with an error:

	==> Starting build()...
	Fetch Python information...
	<string>:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
	<string>:2: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
	  Python version:          3.11
	Traceback (most recent call last):
	  File "C:/_/B/src/gnatcoll-bindings-24.0.0/python3/setup.py", line 217, in <module>
	    sys.exit(app.run())
	             ^^^^^^^^^
	  File "C:/_/B/src/gnatcoll-bindings-24.0.0/setup_support.py", line 372, in run
	    return args.command(args)
	           ^^^^^^^^^^^^^^^^^^
	  File "C:/_/B/src/gnatcoll-bindings-24.0.0/setup_support.py", line 264, in build
	    self.update_config(config, args)
	  File "C:/_/B/src/gnatcoll-bindings-24.0.0/python3/setup.py", line 153, in update_config
	    fetch_python_config(config)
	  File "C:/_/B/src/gnatcoll-bindings-24.0.0/python3/setup.py", line 59, in fetch_python_config
	    static_dir = relocate(config_vars.get('LIBPL', 'libs'))
	                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "C:/_/B/src/gnatcoll-bindings-24.0.0/python3/setup.py", line 45, in relocate
	    rel_path = os.path.relpath(path, build_prefix)
	               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "<frozen ntpath>", line 778, in relpath
	ValueError: path is on mount 'D:', start on mount 'C:'
	==> ERROR: A failure occurred in build().

It happens because the build happens on the 'C:' drive,
while the MSYS installation appears to be on the 'D:' drive

Failed job: https://github.com/msys2/MINGW-packages/actions/runs/7533891323/job/20507271805