Fixed problem with post-install with current glib2.
Before fix it was:

$ pacman -Sv mingw-w64-i686-glib2
Root      : /
Conf File : /etc/pacman.conf
DB Path   : /var/lib/pacman/
Cache Dirs: /var/cache/pacman/pkg/
Hook Dirs : /usr/share/libalpm/hooks/  /etc/pacman.d/hooks/
Lock File : /var/lib/pacman/db.lck
Log File  : /var/log/pacman.log
GPG Dir   : /etc/pacman.d/gnupg/
Targets   : mingw-w64-i686-glib2
warning: mingw-w64-i686-glib2-2.48.0-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-i686-glib2-2.48.0-1

Total Installed Size:  20.02 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring
(1/1) checking package integrity
(1/1) loading package files
(1/1) checking for file conflicts
(1/1) checking available disk space
:: Processing package changes...
(1/1) reinstalling mingw-w64-i686-glib2
D:/MSYS2/mingw32/bin/glib-compile-schemas.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
error: command (/usr/bin/bash /usr/bin/bash -c . /tmp/alpm_F9zHb2/.INSTALL; post_upgrade 2.48.0-1 2.48.0-1 ) failed to execute correctly

Absent file was libpcre-1.dll which can be found in mingw-w64-i686-pcre, mingw-w64-x86_64-pcre receptively.