rust-bindgen: depend on clang-libs
bindgen dynamically depend on libclang, otherwise:
thread 'main' panicked at bindgen\lib.rs:616:27:
Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"

Signed-off-by: Marc-André Lureau <marcandre.lureau@redhat.com>